### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Chocimier**
Hello!

There are still untranslated parts like popup displayed when resizing or Ctrl-Shift-M bar, how to transtate them?

### CODE REVIEW

**Comment by palinek** [comment]
> There are still untranslated parts like popup displayed when resizing or Ctrl-Shift-M bar, how to transtate them?

Are you talking about qterminal? Please, make screenshots, if possible.

**Comment by Chocimier** [comment]
Look at the bottom bar, size popup and action names:
screenshot_20170210_093451
screenshot_20170210_093541
screenshot_20170210_093914

**Comment by yan12125** [comment]
@Chocimier Please open an issue at lxde/qterminal

**Comment by palinek** [comment]
- The "Match case", "Regular expression", "Highlight all matches" of "Find" are in qtermwidget -> https://github.com/lxde/qtermwidget/blob/master/lib/SearchBar.cpp#L39, but there seem to be no "lxqt translation support" in `qtermwidget` at all. @yan12125 do I miss something?

- The "Size" is also in qtermwidget -> the lxde/qtermwidget@42a2d78 made it translatable

- For the shortcuts, we need to do something like [here](https://github.com/lxde/lxqt-panel/blob/master/plugin-sysstat/lxqtsysstatconfiguration.cpp#L54) for all the shortcut texts from [config](https://github.com/lxde/qterminal/blob/master/src/config.h)  in [`PropertiesDialog`](https://github.com/lxde/qterminal/blob/master/src/propertiesdialog.cpp#L258)

@yan12125 can you take care of it, please?

**Comment by yan12125** [comment]
I have a WIP at https://github.com/lxde/qtermwidget/tree/yan12125/wip-translations. Search bar options ("Match case", ...) are working yet filter actions ("Open Link"/"Copy Link Address"/...) not. Need more checking.

Translating shortcuts is the next step.

**Pull request merged**
