### PR TITLE
Update french translations liblxqt, about, notificationd,  openssh-as…

### PR DESCRIPTION
**Pull request by paiiou**
Update french translations liblxqt, about, notificationd,  openssh-askpass, policykit, powermanagement, runner, session, sudo

### CODE REVIEW

**Comment by pmattern** [comment]
Some strings deserve another look at:
- lxqt-config-notificationd_fr.ts: A blank space is missing line 77.
- lxqt-config-powermanagement_fr.ts: Is the additional dot in line 29 purpose?
- lxqt-powermanagement_fr.ts: "Gertion" in line 193, should probably be "Gestion", non? Colon in line 241 missing on purpose? Misunderstanding in line 289. "Disable" isn't an adjective but a verb. So maybe something like "Désactiver l'icône".
- lxqt-config-session_fr.ts: Line 28 not quite right.  "Wait for system tray" doesn't mean wait_ing_ or so. Rather "Launch application xyz only after the panel has started". This is referring to applications which need plugin-tray or plugin-statusnotifier and may crash when they are launched before either of the two is available. Line 79 is referring to autostarting applications in general. IMO plural would be better ("Lancement automatique d&apos;applications" or so).
- lxqt-leave_fr.ts: Additional dot in line 57.
- lxqt-session_fr.ts: No capital letter at the beginning of a new phrase ("Son autostart...") in line 14? Blank space before triple dots in line 27?

That aside let me mention that I'm quite happy to see French translation make it into LXQt finally. It's something I've personally been waiting for since long time.

**Comment by paiiou** [comment]
@pmattern
J'ai l'impression que vous comprenez assez bien le français. Je suis nul en anglais et les traducteurs en ligne ne sont pas toujours fidèles. Je préfère donc vous écrire en français.
J'ai effectué les quelques correction sur le #159, en local, puis :

```
cd ~/git/lxqt-l10n
git add . && git commit --amend -m "Some fixes"
git push --force paiiou transl2_fr:transl2_fr
```

Les modifications sont effectives sur mon fork, mais pas dans lxde/lxqt-l10n

Ai-je fait une erreur ?

**Comment by pmattern** [comment]
You've said before that your English knowledge is rather limited. Basically this is odd as understanding is still needed to translate. But probably the problem isn't as grave as you say as the translations you've made are pretty good as far as I can tell.

As for Git you may very well have invoked the commands stated above from a checkout other than the one of branch `transl2_fr`. The output of `git remote --verbose` and (more importantly) `git branch -vv ---all` should help figuring this out.

That aside nearly all proposals I had made are included in current 5dc9666.
In lxqt-powermanagement_fr.ts, line 193 one error was replaced by another one. In lxqt-config-session_fr.ts line 29 still isn't really accurate if I'm not mistaken. The message is not about a current status but about an action that has basically to be taken. So I think it has to be something like "Attendre l'exécution de system-tray". In lxqt-session_fr.ts "Son" in line 14 has been fixed but there's another issue. Restarting the application in question is not stopped from the next session onwards but until the next session. So probably better "jusqu'à" instead of "à partir de".

**Comment by paiiou** [comment]
this is true for computer terms I begin to know their translation. But for the rest, 'google translations' that saves me.
Here is the result of the command:

```
$ [transl2_fr]git branch -vv --all
  master                              51c802a [origin/master] Update Frech translations (#152)
  transl1_fr                          8101e77 [paiiou/transl1_fr] Fix lxqt-config-appearance_fr.ts
* transl2_fr                          5dc9666 [paiiou/transl2_fr] Some fixes
  remotes/origin/HEAD                 -> origin/master
  remotes/origin/authors-wip          2bc90fc Create AUTHORS in subdirs
  remotes/origin/master               51c802a Update Frech translations (#152)
  remotes/origin/mst_pt               d60ae4c Update Portugese translations
  remotes/origin/releases-0.11.x      ed7ab45 Release 0.11.0: Add changelog
  remotes/origin/use-lxqt-build-tools 1313ce3 Use lxqt-build-tools
  remotes/paiiou/master               51c802a Update Frech translations (#152)
  remotes/paiiou/transl1-fr           8101e77 Fix lxqt-config-appearance_fr.ts
  remotes/paiiou/transl1_fr           8101e77 Fix lxqt-config-appearance_fr.ts
  remotes/paiiou/transl2_fr           5dc9666 Some fixes
```

For the latest bug, I got it today

**Comment by pmattern** [comment]
All issues explained in my previous post are still pending.
But the output of `git branch -vv --all` posted [above](https://github.com/lxde/lxqt-l10n/pull/159#issuecomment-255336007) looks good (except string `[transl2_fr]` between `$` and `git` which seems a bit odd). Could only be that changes exist that haven't been commited yet which you should see by running `git status`.
Anyway it should be possible to fix the missing issues now by editing the files in question and running `git add .`, `git commit --amend` and `git push --force`. As for `git commit --amend` you should change the commit message to something more accurate. The current "Some fixes" is referring to the fixes we've been discussing but not to the commit's content as a whole.

On a side note it would be good if you could put output in code blocks ```. You may just hit button `Edit` (and `Cancel`...) in your previous post which I've edited accordingly or search the web for "github markdown" or something similar.

**Comment by paiiou** [comment]
Hello Peter,
The string `transl2_fr]` is normal. It display the current branch. (a tip found on the internet).
I add a few lines to .bashrc:
`function parse_git_branch {
        git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1]/"
}
PS1="$PS1\$(parse_git_branch)"`

`git status` say:
`[georges@papilou lxqt-l10n]$ [transl2_fr]git status
Sur la branche transl2_fr
Votre branche est à jour avec 'paiiou/transl2_fr'.
rien à valider, la copie de travail est propre`

I now add my last corrections, add, commit and push, as indicated above.

**Comment by pmattern** [comment]
All good regarding the translations now as far as I can tell.

Unfortunately there's another issue which I'm not an expert in either.
If you look through the diff of your commit it's not just the lines of the actual translations which are different but there's lots of additional differences like different referred line numbers of strings missing in the first place. This must have something to do with the way the strings to be translated are extracted from the source code. But I cannot tell whether it's okay like it is right now or there's something wrong (at our side, of course).
@palinek Could you kindly have a look at this?

**Comment by paiiou** [comment]
For your information, I have a `lxqt-trad` directory where I do translations. I then copy to my `git` directory with `mc`

**Comment by palinek** [comment]
> @palinek Could you kindly have a look at this?

It's OK... 

landed in @d384c8b, thanks

**Pull request closed without merging**
