### PR TITLE
Update desktopswitch_nl.ts

### PR DESCRIPTION
**Pull request by Pjotr123**
Complete Dutch translation

### CODE REVIEW

**Comment by palinek** [comment]
@Pjotr123 why don't you make one PR with all the conmits, that you are going to do?

**Comment by Pjotr123** [comment]
@palinek I don't know how to combine my commits.... Actually, I was rather glad that I found out how to translate LXQt on GitHub at all. It's definitely not as simple as Pootle or Transifex. :P 

Can you perhaps instruct me how to combine my future commits?

**Comment by palinek** [comment]
You can simply push new commits into the same branch...

**Comment by Pjotr123** [comment]
How do I do that, while still ensuring that all my commits end up in the right places?

**Comment by palinek** [comment]
How are you creating the commits?

**Comment by Pjotr123** [comment]
Well, I create a new translation file, hit the commit button and then hit the Merge button....

**Comment by pmattern** [comment]
In case you didn't already you may want to have a look at wiki page [Translation](https://github.com/lxde/lxqt/wiki/Translation). Its step-by-step instructions are explaining how to add to existing commits as well.

**Pull request closed without merging**
