### PR TITLE
[wip] Add build system for translations [todo]

### PR DESCRIPTION
**Pull request by palinek**
~~Panel not yet done...~~

ref lxde/lxqt#1043

### CODE REVIEW

**Comment by agaida** [comment]
are there any other requirements for the ts-Files or can they just copied to the translations dir?

**Comment by palinek** [comment]
> are there any other requirements for the ts-Files or can they just copied to the translations dir?

Do you mean direction lxqt-component -> translations repo o vice versa?

**Comment by agaida** [comment]
no - i have prepared a packaging for the simple cases. for this i just copied the files into the directories where they belong to. My question is: Should we keep the commit history of the translation files or will just copy the files be enough?

**Comment by agaida** [comment]
GTM - btw i have prepared the CMakefiles for most other packages, would like to prepare a PR after merging this request.

**Comment by palinek** [comment]
> My question is: Should we keep the commit history of the translation files 

I would say yes (for panel i've spent quite a lot of time to keep the history), but others may think different.

**Comment by agaida** [comment]
http://paste.siduction.org/20160508233052 - looks good so far, i will review it tomorrow

**Comment by palinek** [comment]
Squashed & unified to macro build_component. Now the MakeLists.txt of "simple component" can be as short as:

``` cmake
cmake_minimum_required(VERSION 3.0.2 FATAL_ERROR)

project(lxqt-sudo)

build_component(".")
```

@agaida please, test if everything works as expected.

**Comment by palinek** [comment]
@agaida 
Just fixed the installation path for compton-conf, libfm-qt, lximage-qt ...

**Pull request merged**
