### PR TITLE
Some updating of the danish translations

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by palinek** [comment]
Please, fix the problem reported by tests:
```
48/52 Test #48: /home/travis/build/lxde/lxqt-l10n/lxqt-sudo ..........................................***Failed    0.02 sec
check_ts(/home/travis/build/lxde/lxqt-l10n/lxqt-sudo/lxqt-sudo_da.ts): language(uk) and file name mismatch
```

**Comment by palinek** [comment]
@scootergrisen great, can I squash the commits and merge it that way?

**Comment by scootergrisen** [comment]
I guess. I'm not good at git.

**Comment by palinek** [comment]
landed in @fa2ac0c3, thanks

**Pull request closed without merging**
