### PR TITLE
Polish translation update

### PR DESCRIPTION
**Pull request by napcok**

### CODE REVIEW

**Comment by pmattern** [comment]
You need to make sure that the language setting in tag `language` in line three of `lxqt-config-notificationd_pl.ts` and `lxqt-leave_pl.ts` is consistent with the the one in the files' name which is rightfully set to `pl` only.
Some background information can be found [here](https://github.com/lxde/lxqt/wiki/Translation#language-vs-country-specific-translations).

**Comment by napcok** [comment]
I will update pull request shortly.
Thank you @pmattern

**Comment by napcok** [comment]
Updated.

**Comment by palinek** [comment]
landed in @2b9fadf, thanks

**Pull request closed without merging**
