### PR TITLE
update italian translations

### PR DESCRIPTION
**Pull request by stefonarch**
Updating some new translations and recommitting other old translations already done: seems they got lost with updating .ts files  to recent sources, example: https://github.com/lxde/lxqt-l10n/commit/4ec3916df5097c18269531f98196e5ba08b8dfa3#diff-e0c490f5e3d94ff3dc2f9797b64bd15d line 102 was correct and was changed to 112, affecting also other translations.

### CODE REVIEW

**Comment by palinek** [comment]
Can you rebase, please?

**Comment by stefonarch** [comment]
Uhm, I'm afraid it's quite over my understanding of git  here, I did it to squash more commits into one but here?

**Comment by palinek** [comment]
...merged into 580d06a1. @stefonarch please, check if it is OK.

**Comment by stefonarch** [comment]
Compiled and looks ok, thanks!

**Pull request closed without merging**
