### PR TITLE
Almost completed Ukrainian translation

### PR DESCRIPTION
**Pull request by knedlyk**
Hi, 
Please accept Ukrainian translation. It is almost complete, a few strings are not translated. 
Regards,
Yarema

### CODE REVIEW

**Comment by palinek** [comment]
@knedlyk can you, please, squash the commits into one (or into few logical groups) to avoid such commits messages as "Ukrainian translation update #X" ?

**Comment by knedlyk** [comment]
What is the best way to do that? Next time I'll avoid "#X" and be more precise in comments.

**Comment by palinek** [comment]
> What is the best way to do that? Next time I'll avoid "#X" and be more precise in comments.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

Or if you don't mind, we can do it on behalf of you (your authorship will be preserved).

**Comment by knedlyk** [comment]
OK, done. What I have to do next?
Sorry for my silly questions, I'm not a git guru.

**Comment by palinek** [comment]
Huh...you did it wrong, now there are even more commits here (and even a merge commit)...

This -> https://github.com/lxde/lxqt-l10n/compare/ukr_pr_162 is how I would squash it... can I merge it that way?

**Comment by knedlyk** [comment]
Yes, do it for me, pls. Thanks!

**Comment by palinek** [comment]
landed in @6d2de75, many thanks

**Pull request closed without merging**
