### PR TITLE
Complete Spanish translation

### PR DESCRIPTION
**Pull request by micrococo**
Completed existing Spanish translations and added the missing ones.

### CODE REVIEW

**Comment by agaida** [comment]
anyone who speak spanish?

**Comment by tsujan** [comment]
I use Google translate with random strings to check translations. I did so right now and it seemed OK.

**Comment by palinek** [comment]
@micrococo please, fix all problems reported, starting here -> https://travis-ci.org/lxqt/lxqt-l10n/builds/372421439#L5669

**Comment by ghost** [comment]
Hi, I speak spanish and the translations looks good for me, only a suggestion to @micrococo when you translate "widget" in appearance https://github.com/lxqt/lxqt-l10n/pull/344/commits/e9da3b331c5905e8f5b4ba500cc078e7dd42123b  you can use "Controles" instead of "Miniaplicaciones" because we are talking about application widgets (like QLineEdit, QPushButtons...) not plugins (like panel "widgets")

**Comment by micrococo** [comment]
Thanks for pointing it out and the review @gabretana.

**Comment by palinek** [comment]
@micrococo  thanks.

**Pull request merged**
